BLOCK_SITE: []
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  label: active
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK: []
MAX_POSTS_NUM: 50
OUTDATE_CLEAN: 100
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: https://cdn.jsdelivr.net/gh/Bytelv/friends@output/friends.json
  list: []
